<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEe9jeFz\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEe9jeFz/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerEe9jeFz.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerEe9jeFz\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerEe9jeFz\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'Ee9jeFz',
    'container.build_id' => '2b96c10a',
    'container.build_time' => 1788525387,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEe9jeFz');
