<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEOBvuHk\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEOBvuHk/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerEOBvuHk.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerEOBvuHk\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerEOBvuHk\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'EOBvuHk',
    'container.build_id' => '876f731e',
    'container.build_time' => 1788976894,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEOBvuHk');
