<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ7xjED9\Glpi_Kernel_KernelDevelopmentDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ7xjED9/Glpi_Kernel_KernelDevelopmentDebugContainer.php') {
    touch(__DIR__.'/ContainerZ7xjED9.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelDevelopmentDebugContainer::class, false)) {
    \class_alias(\ContainerZ7xjED9\Glpi_Kernel_KernelDevelopmentDebugContainer::class, Glpi_Kernel_KernelDevelopmentDebugContainer::class, false);
}

return new \ContainerZ7xjED9\Glpi_Kernel_KernelDevelopmentDebugContainer([
    'container.build_hash' => 'Z7xjED9',
    'container.build_id' => 'f62c9f61',
    'container.build_time' => 1788976370,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ7xjED9');
