CREATE TABLE IF NOT EXISTS `glpi_plugin_ativaupdater_releases` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `version` varchar(32) NOT NULL,
  `original_filename` varchar(255) NOT NULL,
  `stored_filename` varchar(255) NOT NULL,
  `file_path` varchar(512) NOT NULL,
  `file_size` bigint(20) unsigned NOT NULL,
  `sha256` varchar(64) NOT NULL,
  `created_at` datetime NOT NULL,
  `created_by` int(11) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '0',
  `allow_downgrade` tinyint(1) NOT NULL DEFAULT '0',
  `activated_at` datetime NULL,
  `activated_by` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `version` (`version`),
  KEY `active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `glpi_plugin_ativaupdater_clients` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `machine_guid` varchar(64) NOT NULL,
  `hostname` varchar(255) NOT NULL,
  `updater_version` varchar(32) NOT NULL DEFAULT '',
  `installed_version` varchar(32) NOT NULL DEFAULT '',
  `available_version` varchar(32) NOT NULL DEFAULT '',
  `wallpaper_client_version` varchar(32) NOT NULL DEFAULT '',
  `glpi_agent_version` varchar(32) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL DEFAULT 'checking',
  `message` text NULL,
  `last_ip` varchar(64) NOT NULL DEFAULT '',
  `last_check` datetime NOT NULL,
  `check_requested_at` datetime NULL,
  `check_acknowledged_at` datetime NULL,
  `check_request_seq` int unsigned NOT NULL DEFAULT '0',
  `check_ack_seq` int unsigned NOT NULL DEFAULT '0',
  `command` varchar(32) NULL,
  `diagnostics_log` mediumtext NULL,
  `diagnostics_at` datetime NULL,
  `recovery_note` varchar(255) NULL,
  `recovery_at` datetime NULL,
  `install_started_at` datetime NULL,
  `install_log` mediumtext NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `machine_guid` (`machine_guid`),
  KEY `status` (`status`),
  KEY `last_check` (`last_check`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
